# Generated by Django 4.2.5 on 2023-09-29 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_creation_datetime_album_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='songs/images/')),
                ('audio_file', models.FileField(upload_to='songs/audio/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='albums.album')),
            ],
        ),
    ]
