# Generated by Django 4.2.5 on 2023-09-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='songs/audio/'),
        ),
    ]
